// ============================================================
// @APP_NAME@ Firefox App Profile
// Generated by Caelestia Web App Installer
// ============================================================

user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.startup.firstrunSkipsHomepage", true);
user_pref("browser.startup.homepage", "@APP_URL@");
user_pref("browser.startup.page", 1);
// Dedicated WebApp profiles must never show Firefox crash/session recovery UI.
// After an OS reboot Firefox may treat an abruptly terminated app window as a crash.
// Always start the configured app URL instead of restoring the previous browser session.
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.resume_session_once", false);
// Firefox tracks a separate onboarding infobar that offers to open previous
// tabs even when automatic session restore is disabled. Dedicated WebApps
// always open their configured URL, so suppress that browser-only suggestion.
user_pref("browser.startup.couldRestoreSession.count", -1);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuitShortcut", false);

// Keep media/WebRTC enabled for web apps that use calls/voice.
user_pref("media.navigator.enabled", true);
user_pref("media.peerconnection.enabled", true);
