#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/caelestia-webapps"
CACHE_DIR="$CACHE_ROOT/store-icons-v6"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/caelestia-webapps"
LOG_FILE="$STATE_DIR/icon-pipeline.log"
mkdir -p "$CACHE_DIR" "$STATE_DIR"
: > "$LOG_FILE"

is_svg() { [[ -s "$1" ]] && grep -qi '<svg' "$1"; }
is_png() { [[ -s "$1" ]] || return 1; [[ "$(od -An -tx1 -N8 "$1" 2>/dev/null | tr -d ' \n')" == "89504e470d0a1a0a" ]]; }
is_webp() { [[ -s "$1" ]] || return 1; [[ "$(dd if="$1" bs=1 count=4 2>/dev/null)" == "RIFF" ]] && [[ "$(dd if="$1" bs=1 skip=8 count=4 2>/dev/null)" == "WEBP" ]]; }

fetch_typed() {
    local url="$1" target="$2" type="$3" tmp
    [[ -n "$url" ]] || return 1
    command -v curl >/dev/null 2>&1 || return 1
    tmp="$(mktemp)"
    if curl --fail --location --silent --show-error --retry 2 --retry-delay 1 \
        --connect-timeout 5 --max-time 20 "$url" -o "$tmp" 2>/dev/null; then
        case "$type" in
            svg) is_svg "$tmp" && { mv "$tmp" "$target"; return 0; } ;;
            png) is_png "$tmp" && { mv "$tmp" "$target"; return 0; } ;;
            webp) is_webp "$tmp" && { mv "$tmp" "$target"; return 0; } ;;
        esac
    fi
    rm -f "$tmp"
    return 1
}

fetch_auto() {
    local url="$1" base="$2" tmp
    [[ -n "$url" ]] || return 1
    command -v curl >/dev/null 2>&1 || return 1
    tmp="$(mktemp)"
    if curl --fail --location --silent --show-error --retry 2 --retry-delay 1 \
        --connect-timeout 5 --max-time 20 "$url" -o "$tmp" 2>/dev/null; then
        if is_svg "$tmp"; then mv "$tmp" "${base}.svg"; return 0; fi
        if is_png "$tmp"; then mv "$tmp" "${base}.png"; return 0; fi
        if is_webp "$tmp"; then mv "$tmp" "${base}.webp"; return 0; fi
    fi
    rm -f "$tmp"
    return 1
}

emit_progress() {
    [[ "${CAELESTIA_WEBAPPS_PROGRESS:-0}" == "1" ]] || return 0
    local current="$1" total="$2" app_id="$3" result="$4" permille
    permille=$((160 + current * 660 / (total > 0 ? total : 1)))
    printf '{"stage":"icons","label":"WebApp Icons","detail":"%d/%d · %s · %s","progress":0.%03d,"state":"running"}\n' \
        "$current" "$total" "$app_id" "$result" "$permille"
}

log_result() {
    local status="$1" app_id="$2" icon_id="$3" result="$4"
    printf '[%-10s] %-22s %-28s %s\n' "$status" "$app_id" "${icon_id:--}" "$result" >> "$LOG_FILE"
}

shopt -s nullglob
confs=("$ROOT_DIR"/apps/*.conf)
total=${#confs[@]}
current=0
resolved=0
unresolved=0

for conf in "${confs[@]}"; do
  current=$((current + 1))
  # shellcheck disable=SC1090
  source "$conf"

  icon_id="${ICON_ID:-}"
  icon_name="${ICON_NAME:-$APP_ID}"
  provider="${ICON_PROVIDER:-}"
  base="$CACHE_DIR/${icon_name}"
  result=""

  # Gemini is a known Qt/Quickshell rendering exception: the Dashboard Icons SVG
  # resolves correctly but is not rendered reliably in the manager. Prefer the
  # PNG generated by the same Dashboard Icons project. Do this even when an old
  # Gemini SVG already exists in the cache.
  if [[ "$APP_ID" == "gemini" && "$provider" == "dashboard-icons" && -n "$icon_id" ]]; then
      if is_png "${base}.png"; then
          result="cached-png-preferred"
      elif fetch_typed "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/png/${icon_id}.png" "${base}.png" png; then
          result="dashboard-png-preferred"
      fi
  fi

  if [[ -z "$result" ]] && { is_svg "${base}.svg" || is_png "${base}.png" || is_webp "${base}.webp"; }; then
      result="cached"
  fi

  # 1. Dashboard Icons is always the primary source for dashboard-icons entries.
  # Use only explicit ICON_ID values; never derive/guess a slug from the app name.
  if [[ -z "$result" && "$provider" == "dashboard-icons" && -n "$icon_id" ]]; then
      if fetch_typed "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/${icon_id}.svg" "${base}.svg" svg; then
          result="dashboard-svg"
      elif fetch_typed "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/png/${icon_id}.png" "${base}.png" png; then
          result="dashboard-png"
      elif fetch_typed "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/webp/${icon_id}.webp" "${base}.webp" webp; then
          result="dashboard-webp"
      fi
  fi

  # 2. Explicit curated non-Dashboard source. This is used only where the catalog
  # intentionally points at another provider (for example LobeHub).
  if [[ -z "$result" && "$provider" != "dashboard-icons" && -n "${ICON_URL:-}" ]]; then
      if fetch_auto "$ICON_URL" "$base"; then
          result="curated-external"
      fi
  fi

  # 3. Curated bundled app icon. Only real app-specific assets are cacheable.
  # The generic globe is deliberately excluded, otherwise one temporary network
  # failure would permanently poison the cache again.
  if [[ -z "$result" && -n "${ICON_LOCAL_FILE:-}" && "$ICON_LOCAL_FILE" != *"webapp-generic.svg" ]]; then
      if is_svg "$ICON_LOCAL_FILE"; then
          cp "$ICON_LOCAL_FILE" "${base}.svg"
          result="bundled-local"
      elif is_png "$ICON_LOCAL_FILE"; then
          cp "$ICON_LOCAL_FILE" "${base}.png"
          result="bundled-local"
      fi
  fi

  # 4. Website favicon fallback. This is a real app/site icon and may therefore
  # be cached locally. It restores the useful fallback from fix2 without ever
  # treating the generic globe as a successful resolution.
  if [[ -z "$result" && -n "${APP_URL:-}" ]]; then
      favicon_url="https://www.google.com/s2/favicons?domain_url=${APP_URL}&sz=128"
      if fetch_typed "$favicon_url" "${base}.png" png; then
          result="website-favicon"
      fi
  fi

  if [[ -n "$result" ]]; then
      resolved=$((resolved + 1))
      log_result "OK" "$APP_ID" "$icon_id" "$result"
  else
      unresolved=$((unresolved + 1))
      result="unresolved"
      log_result "UNRESOLVED" "$APP_ID" "$icon_id" "generic runtime fallback"
  fi
  emit_progress "$current" "$total" "$APP_ID" "$result"
done

printf '\nSUMMARY total=%d resolved=%d unresolved=%d cache=%s\n' "$total" "$resolved" "$unresolved" "$CACHE_DIR" >> "$LOG_FILE"

if [[ "${CAELESTIA_WEBAPPS_PROGRESS:-0}" == "1" ]]; then
    state="done"
    [[ "$unresolved" -eq 0 ]] || state="warning"
    printf '{"stage":"icons-summary","label":"WebApp Icons","detail":"%d/%d lokal aufgelöst · %d Fallback(s)","progress":0.830,"state":"%s"}\n' \
        "$resolved" "$total" "$unresolved" "$state"
fi

[[ "$unresolved" -eq 0 ]]
